version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - chmod +x *.sh

artifacts:
  files:
    - ./appspec.yml
    - ./app_start.sh
    - ./app_stop.sh
    - ./app_clean.sh
    - ./logback.xml
    - ./irunninglog-main/target/irunninglog.jar
