steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/api', '.']
images: ['gcr.io/$PROJECT_ID/api']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - [DEPLOYMENT-NAME]
  - [CONTAINER]=gcr.io/[PROJECT-ID]/[IMAGE]:[TAG]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=irunninglog-api'
